Minor file IO bug fix
Fixed a minor bug related to file IO.
Description:
Not providing a .rad file for read_from_CIF, read_from_V1 and read_from_ARC resulted in a type error.

Code to reproduce:
from pyzeo.netstorage import AtomNetwork
atmnet = AtomNetwork.read_from_CIF("EDI.cif")

Example error output:
File "src/pyzeo/extension.pyx", line 512, in pyzeo.extension.AtomNetwork.read_from_CIF
TypeError: expected bytes, NoneType found

Comment:
A unit test "test_read_file.py" was added for validation.